"""Create handicap_adjustment table

Revision ID: 90077322c263
Revises: 85f484d6113c
Create Date: 2025-08-10 14:35:07.786815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90077322c263'
down_revision: Union[str, Sequence[str], None] = '85f484d6113c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handicap_adjustment',
    sa.Column('stableford_score', sa.Integer(), nullable=False),
    sa.Column('adjustment', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('stableford_score')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handicap_adjustment')
    # ### end Alembic commands ###
