"""Add Round and HoleScore models

Revision ID: 9e69de653dc9
Revises: de9ecf1305e0
Create Date: 2025-08-08 10:59:12.953899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e69de653dc9'
down_revision: Union[str, Sequence[str], None] = 'de9ecf1305e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('slope_rating', sa.Float(), nullable=True),
    sa.Column('hole_pars', sa.String(length=500), nullable=True),
    sa.Column('hole_stroke_indices', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hole_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stableford_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('handicap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('date_played', sa.String(length=80), nullable=False),
    sa.Column('gross_score_front_9', sa.Integer(), nullable=True),
    sa.Column('nett_score_front_9', sa.Integer(), nullable=True),
    sa.Column('stableford_front_9', sa.Integer(), nullable=True),
    sa.Column('gross_score_back_9', sa.Integer(), nullable=True),
    sa.Column('nett_score_back_9', sa.Integer(), nullable=True),
    sa.Column('stableford_back_9', sa.Integer(), nullable=True),
    sa.Column('gross_score_total', sa.Integer(), nullable=True),
    sa.Column('nett_score_total', sa.Integer(), nullable=True),
    sa.Column('stableford_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_courses',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'course_id')
    )
    op.create_table('tournament_players',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_players')
    op.drop_table('tournament_courses')
    op.drop_table('round')
    op.drop_table('tournament')
    op.drop_table('player')
    op.drop_table('hole_score')
    op.drop_table('course')
    # ### end Alembic commands ###
