"""Add handicap_index and playing_handicap to Round model

Revision ID: fa4b40fac279
Revises: 
Create Date: 2025-08-09 13:27:23.493345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4b40fac279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_handicap_index', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('player_playing_handicap', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_column('player_playing_handicap')
        batch_op.drop_column('player_handicap_index')

    # ### end Alembic commands ###
